import type { Metadata } from 'next';
import { LineIcon } from '../../components/LineIcon';
import { PageShell } from '../../components/SiteChrome';
import { ServiceShowcase, type ServiceShowcaseItem } from '../../components/ServiceShowcase';

export const metadata: Metadata = { title: 'Mobile Phone Repair Services | J Bells Smart Phone Service Center', description: 'Display, battery, charging port, camera, speaker, water damage and software repairs handled at our Trivandrum service counter.', alternates: { canonical: '/services' } };

const services: ServiceShowcaseItem[] = [
  { number: '01', name: 'Display Replacement', eyebrow: 'SCREEN CARE', title: "Cracked screen? Let's fix that.", description: 'Cracked glass, dead touch zones or a black patch under the screen — we replace the full display assembly and test the touch and the image before returning the phone.', image: '/images/services/01-display.png', imageAlt: 'Representative service photograph of smartphone display replacement', icon: 'smartphone' },
  { number: '02', name: 'Camera Repair', eyebrow: 'CAMERA CARE', title: 'When your camera stops cooperating.', description: 'Blurry shots, a camera that will not open, or a cracked back glass — we look at the camera module and tell you whether it needs a clean, a reseat, or a replacement.', image: '/images/services/02-camera.png', imageAlt: 'Representative service photograph of smartphone camera repair', icon: 'camera' },
  { number: '03', name: 'Battery Replacement', eyebrow: 'POWER CARE', title: "A battery that can't make it through the day?", description: 'Sudden shutdowns, fast drain, or a back panel starting to lift — bring it in. We check the symptoms and replace the cell when it is genuinely the cause.', image: '/images/services/03-battery.png', imageAlt: 'Representative service photograph of smartphone battery replacement', icon: 'battery' },
  { number: '04', name: 'Speaker Repair', eyebrow: 'AUDIO CARE', title: "Can't hear clearly anymore?", description: 'Muffled calls, quiet media or a silent earpiece — we look at the speaker grille and the module. Often the fix is small; sometimes the module has gone.', image: '/images/services/04-speaker.png', imageAlt: 'Representative service photograph of smartphone speaker repair', icon: 'audio' },
  { number: '05', name: 'Water Damage Repair', eyebrow: 'LIQUID CHECK', title: 'Dropped it in water? Bring it in.', description: 'Do not charge it, do not try to dry it with heat. Power it off and bring it in as soon as you can — the sooner we open it, the better the chance of saving the board.', image: '/images/services/05-water-damage.png', imageAlt: 'Representative service photograph of smartphone water damage inspection', icon: 'shield' },
  { number: '06', name: 'Unlock & Password Reset', eyebrow: 'ACCESS SUPPORT', title: 'Locked out of your device?', description: 'Forgotten PIN, FRP lock after a reset, or a second-hand phone you cannot get into — we will look at the device, tell you what is supported, and discuss the data implications first.', image: '/images/services/06-unlock.png', imageAlt: 'Representative service photograph of smartphone unlock and password reset', icon: 'check' },
  { number: '07', name: 'Charging Port Repair', eyebrow: 'CHARGE CARE', title: "Not charging like it should?", description: 'Cable has to sit at one angle, or there is no charge at all — usually lint packed in the port or a worn connector. We clean, inspect and replace the port when needed.', image: '/images/services/07-charging-port.png', imageAlt: 'Representative service photograph of smartphone charging port repair', icon: 'usb' },
  { number: '08', name: 'Data Recovery', eyebrow: 'DATA CARE', title: 'Your data matters.', description: 'Photos, contacts and chat history often matter more than the phone. We look at what is still accessible and talk through the realistic options before doing anything.', image: '/images/services/08-data-recovery.png', imageAlt: 'Representative service photograph of smartphone data recovery', icon: 'scan' },
  { number: '09', name: 'Software Solutions', eyebrow: 'SYSTEM CARE', title: "When the problem isn't the hardware.", description: 'Boot loops, freezes, updates that broke something — we check the symptoms, the storage and the logs before recommending a fix, and we keep data loss in mind throughout.', image: '/images/services/09-software.png', imageAlt: 'Representative service photograph of smartphone software troubleshooting', icon: 'cpu' },
  { number: '10', name: 'All Mobile Accessories', eyebrow: 'EVERYDAY CARE', title: 'The little things your phone needs.', description: 'Tempered glass, cases, cables and chargers. Ask at the counter and we will point you to what fits the phone and how you actually use it.', image: '/images/services/10-accessories.png', imageAlt: 'Representative service photograph of mobile accessories', icon: 'badge' },
];

export default function ServicesPage() { return <PageShell active="services">
  <section className="page-hero services-hero"><p className="eyebrow">WHAT WE DO</p><h1>Smartphone repair<br /><span>services we</span><br />handle at the bench.</h1><p className="lede">Display, battery, charging, camera, speaker, water damage, software and more — done at our Trivandrum counter.</p><div className="services-scroll-cue"><span>SCROLL TO EXPLORE SERVICES</span><i /></div></section>
  <section className="showcase-intro inner-section"><p className="eyebrow">THE SERVICE CATALOGUE</p><h2>One phone at a time.<br /><span>One repair at a time.</span></h2><p className="body-copy">Tell us what your phone is doing. We will tell you what we think it needs.</p></section>
  <ServiceShowcase services={services} />
  <section className="services-closing inner-section"><p className="eyebrow">NOT SURE WHAT YOUR PHONE NEEDS?</p><h2>Tell us what&apos;s<br /><span>wrong.</span></h2><p className="lede">Bring it in or send a quick message — we will figure out the next step together.</p><a className="button" href="/contact">Contact J Bells <LineIcon name="arrowUpRight" /></a></section>
 </PageShell> }
