import type { Metadata } from 'next';
import { LineIcon } from '../../components/LineIcon';
import { PageShell } from '../../components/SiteChrome';
import { ServiceShowcase, type ServiceShowcaseItem } from '../../components/ServiceShowcase';

export const metadata: Metadata = { title: 'Mobile Phone Repair Services | J.Bells', description: 'Professional smartphone repair and mobile-care services from J.Bells Smart Phone Service Centre.' };

const services: ServiceShowcaseItem[] = [
  { number: '01', name: 'Display Replacement', eyebrow: 'SCREEN CARE', title: "Cracked screen? Let's fix that.", description: 'A damaged screen can make even a perfectly working phone difficult to use. Our display replacement service focuses on restoring clear visuals and responsive touch functionality.', image: '/images/services/01-display.png', imageAlt: 'Representative service photograph of smartphone display replacement', icon: 'smartphone' },
  { number: '02', name: 'Camera Repair', eyebrow: 'CAMERA CARE', title: 'When your camera stops cooperating.', description: 'Blurred images, a camera that will not open, or a lens that is no longer focusing can make a phone feel broken. We inspect the camera system and work through the issue carefully.', image: '/images/services/02-camera.png', imageAlt: 'Representative service photograph of smartphone camera repair', icon: 'camera' },
  { number: '03', name: 'Battery Replacement', eyebrow: 'POWER CARE', title: "A battery that can't make it through the day?", description: 'If your phone struggles to hold a charge or shuts down unexpectedly, the battery may need attention. We can inspect the device and replace the battery when required.', image: '/images/services/03-battery.png', imageAlt: 'Representative service photograph of smartphone battery replacement', icon: 'battery' },
  { number: '04', name: 'Speaker Repair', eyebrow: 'AUDIO CARE', title: "Can't hear clearly anymore?", description: 'Muffled calls, low media volume or a speaker that has gone quiet can often be traced to a specific component. We check the audio path and restore clear everyday sound where possible.', image: '/images/services/04-speaker.png', imageAlt: 'Representative service photograph of smartphone speaker repair', icon: 'audio' },
  { number: '05', name: 'Water Damage Repair', eyebrow: 'LIQUID CHECK', title: 'Dropped it in water? Bring it in.', description: 'Liquid damage can continue to affect a phone after the outside looks dry. An early inspection helps us understand what has been affected and what repair options are available.', image: '/images/services/05-water-damage.png', imageAlt: 'Representative service photograph of smartphone water damage inspection', icon: 'shield' },
  { number: '06', name: 'Unlock & Password Reset', eyebrow: 'ACCESS SUPPORT', title: 'Locked out of your device?', description: 'When access becomes the problem, we help with supported unlock and password-reset solutions. We will first understand the device and the access issue before recommending the next step.', image: '/images/services/06-unlock.png', imageAlt: 'Representative service photograph of smartphone unlock and password reset', icon: 'check' },
  { number: '07', name: 'Charging Port Repair', eyebrow: 'CHARGE CARE', title: "Not charging like it should?", description: 'A loose connection, debris or a worn charging port can make every charge frustrating. We inspect the port and connection so the actual cause can be addressed.', image: '/images/services/07-charging-port.png', imageAlt: 'Representative service photograph of smartphone charging port repair', icon: 'usb' },
  { number: '08', name: 'Data Recovery', eyebrow: 'DATA CARE', title: 'Your data matters.', description: 'Photos, contacts and files can feel more valuable than the device itself. We assess the phone and explore practical recovery options for data that is still accessible.', image: '/images/services/08-data-recovery.png', imageAlt: 'Representative service photograph of smartphone data recovery', icon: 'scan' },
  { number: '09', name: 'Software Solutions', eyebrow: 'SYSTEM CARE', title: "When the problem isn't the hardware.", description: 'Freezing, unexpected errors and software trouble can be difficult to diagnose at home. We look at the symptoms, check the system and help identify a sensible software solution.', image: '/images/services/09-software.png', imageAlt: 'Representative service photograph of smartphone software troubleshooting', icon: 'cpu' },
  { number: '10', name: 'All Mobile Accessories', eyebrow: 'EVERYDAY CARE', title: 'The little things your phone needs.', description: 'The right accessory can make daily phone use easier and help protect the device. Ask us about practical mobile accessories for your setup and everyday routine.', image: '/images/services/10-accessories.png', imageAlt: 'Representative service photograph of mobile accessories', icon: 'badge' },
];

export default function ServicesPage() { return <PageShell active="services">
  <section className="page-hero services-hero"><p className="eyebrow">WHAT WE DO</p><h1>Professional<br /><span>Smartphone Repair</span><br />Services</h1><p className="lede">Reliable smartphone repair and mobile-care solutions, with careful diagnosis at every step.</p><div className="services-scroll-cue"><span>SCROLL TO EXPLORE SERVICES</span><i /></div></section>
  <section className="showcase-intro inner-section"><p className="eyebrow">THE SERVICE CATALOGUE</p><h2>One problem at a time.<br /><span>One careful repair at a time.</span></h2><p className="body-copy">Tell us what your phone is doing. We will help you understand what it needs.</p></section>
  <ServiceShowcase services={services} />
  <section className="services-closing inner-section"><p className="eyebrow">NOT SURE WHAT YOUR PHONE NEEDS?</p><h2>Tell us what&apos;s<br /><span>wrong.</span></h2><p className="lede">We will help you figure out the next step.</p><a className="button" href="/contact">Contact J.Bells <LineIcon name="arrowUpRight" /></a></section>
 </PageShell> }