import type { Metadata } from 'next';
import { EnquiryForm } from '../../components/EnquiryForm';
import { LineIcon } from '../../components/LineIcon';
import { PageShell } from '../../components/SiteChrome';
import { locations } from '../../lib/business';

export const metadata: Metadata = { title: 'Contact J.Bells | Smart Phone Service Centre', description: 'Contact J.Bells Smart Phone Service Centre for smartphone repair, troubleshooting and mobile-care enquiries.' };

export default function ContactPage() { return <PageShell active="contact">
  <section className="page-hero contact-hero"><p className="eyebrow">GET IN TOUCH</p><h1>Get Your Phone<br /><span>Fixed by the</span><br />Experts</h1><p className="lede">Have a repair or mobile-care question? Find a J.Bells location or send an enquiry to get started.</p></section>
  <section className="inner-section contact-layout"><div><p className="eyebrow">SEND AN ENQUIRY</p><h2>Tell us what<br /><span>you need.</span></h2><p className="body-copy">Share a few details about your device and the service you are looking for. A service team can follow up through the handler connected to this form.</p></div><EnquiryForm /></section>
  <section className="inner-section find-us"><div className="section-head"><div><p className="eyebrow">FIND US</p><h2>Visit a J.Bells<br /><span>location.</span></h2></div><p className="body-copy">Use the official Google Maps listings below for directions and the most current place information.</p></div><div className="locations-grid">{locations.map((location) => <article className="location-card location-card-large" key={location.name}><div className="location-card-copy"><div className="location-icon"><LineIcon name="search" /></div><p className="eyebrow">J.BELLS LOCATION</p><h3>{location.name}</h3><p className="coordinates">Coordinates {location.latitude}, {location.longitude}</p><div className="location-actions"><a className="button" href={location.mapUrl} target="_blank" rel="noreferrer">Get Directions <LineIcon name="arrowUpRight" /></a><a className="text-link" href={location.mapUrl} target="_blank" rel="noreferrer">Open in Google Maps <LineIcon name="arrowUpRight" /></a></div></div><iframe title={`Map for ${location.name}`} loading="lazy" src={`https://www.google.com/maps?q=${location.latitude},${location.longitude}&z=15&output=embed`} referrerPolicy="no-referrer-when-downgrade" /></article>)}</div></section>
  <section className="inner-section reviews-note"><p className="eyebrow">GOOGLE REVIEWS</p><h2>Loved by our<br /><span>customers.</span></h2><div className="review-placeholder"><LineIcon name="shield" /><div><h3>Verified listing information</h3><p>Current review ratings, counts and review text are not displayed until they can be reliably verified from each live Google listing.</p></div>{locations.map((location) => <a key={location.name} href={location.mapUrl} target="_blank" rel="noreferrer">Read reviews on Google <LineIcon name="arrowUpRight" /></a>)}</div></section>
 </PageShell> }
