import type { Metadata } from 'next';
import { EnquiryForm } from '../../components/EnquiryForm';
import { LineIcon } from '../../components/LineIcon';
import { PageShell } from '../../components/SiteChrome';
import { locations } from '../../lib/business';

export const metadata: Metadata = { title: 'Contact J Bells | Smart Phone Service Center', description: 'Reach J Bells in Trivandrum — drop in, call, message on WhatsApp, or send a repair enquiry.', alternates: { canonical: '/contact' } };

export default function ContactPage() { return <PageShell active="contact">
  <section className="page-hero contact-hero"><p className="eyebrow">GET IN TOUCH</p><h1>Drop in, call,<br /><span>or send us</span><br />a message.</h1><p className="lede">Have a repair question or want to confirm a part before you come by? Find a J Bells location below or send us an enquiry.</p></section>
  <section className="inner-section contact-layout"><div><p className="eyebrow">SEND AN ENQUIRY</p><h2>Tell us what<br /><span>you need.</span></h2><p className="body-copy">A few details about the phone and the problem is enough. We will reply with what we think the next step should be.</p></div><EnquiryForm /></section>
  <section className="inner-section find-us"><div className="section-head"><div><p className="eyebrow">FIND US</p><h2>Visit a J.Bells<br /><span>location.</span></h2></div><p className="body-copy">Use the Google Maps links below for directions and the most up-to-date opening hours.</p></div><div className="locations-grid">{locations.map((location) => <article className="location-card location-card-large" key={location.name}><div className="location-card-copy"><div className="location-icon"><LineIcon name="search" /></div><p className="eyebrow">J.BELLS LOCATION</p><h3>{location.name}</h3><p className="coordinates">Coordinates {location.latitude}, {location.longitude}</p><div className="location-actions"><a className="button" href={location.mapUrl} target="_blank" rel="noreferrer">Get Directions <LineIcon name="arrowUpRight" /></a><a className="text-link" href={location.mapUrl} target="_blank" rel="noreferrer">Open in Google Maps <LineIcon name="arrowUpRight" /></a></div></div><iframe title={`Map for ${location.name}`} loading="lazy" src={`https://www.google.com/maps?q=${location.latitude},${location.longitude}&z=15&output=embed`} referrerPolicy="no-referrer-when-downgrade" /></article>)}</div></section>
  <section className="inner-section reviews-note"><p className="eyebrow">GOOGLE REVIEWS</p><h2>See what people<br /><span>are saying.</span></h2><div className="review-placeholder"><LineIcon name="shield" /><div><h3>Reviews are pulled from Google</h3><p>We do not display review scores or snippets until we can verify them on each live Google listing. Tap through to read the latest reviews.</p></div>{locations.map((location) => <a key={location.name} href={location.mapUrl} target="_blank" rel="noreferrer">Read reviews on Google <LineIcon name="arrowUpRight" /></a>)}</div></section>
 </PageShell> }
