import type { Metadata } from 'next';
import { LineIcon, type IconName } from '../../components/LineIcon';
import { PageShell } from '../../components/SiteChrome';
import { locations } from '../../lib/business';

export const metadata: Metadata = { title: 'About J.Bells | Smart Phone Service Centre', description: 'Learn about J.Bells Smart Phone Service Centre, serving customers with smartphone repair and mobile-care services since 2010.' };
const reasons: [string, string, string, IconName][] = [['01', 'EXPERT TECHNICIANS', 'Thoughtful diagnosis and careful handling for every device.', 'wrench'], ['02', 'QUALITY PARTS', 'A quality-focused approach to mobile repair and service.', 'shield'], ['03', 'QUICK SERVICE', 'A straightforward service experience focused on getting you moving.', 'check'], ['04', 'CUSTOMER CARE', 'Clear communication and support throughout your visit.', 'badge'], ['05', 'AFFORDABLE PRICING', 'Practical mobile-care solutions with value in mind.', 'calendar']];

export default function AboutPage() { return <PageShell active="about">
  <section className="page-hero"><p className="eyebrow">ABOUT J.BELLS</p><h1>Your Trusted<br /><span>Mobile Care</span><br />Experts</h1><p className="lede">J.Bells has been serving customers since 2010 with smartphone repair, troubleshooting and related mobile-care services.</p></section>
  <section className="inner-section about-story"><div><p className="eyebrow">OUR STORY</p><h2>Built around<br /><span>better repairs.</span></h2></div><div className="story-copy"><p className="body-copy">J.Bells Smart Phone Service Centre is focused on helping people keep their phones working at their best. Our work brings together careful diagnosis, repair and practical support for everyday mobile needs.</p><div className="since-card"><span className="since-number">2010</span><span className="since-label">SERVING CUSTOMERS<br />SINCE 2010</span></div></div></section>
  <section className="about-values inner-section"><p className="eyebrow">WHY CHOOSE J.BELLS</p><h2>Precision inside<br /><span>and out.</span></h2><div className="feature-grid">{reasons.map(([n, title, text, icon]) => <article className="feature-item" key={n}><b>{n}</b><LineIcon name={icon} /><h3>{title}</h3><p>{text}</p></article>)}</div></section>
  <section className="iso-section inner-section"><div className="iso-mark"><LineIcon name="shield" /></div><div><p className="eyebrow">A TRUST SIGNAL</p><h2>ISO Certified<br /><span>Service Centre</span></h2><p className="body-copy">J.Bells is presented as an ISO Certified Service Centre. Certification details are not listed here because no certificate number, body, date or scope has been provided.</p></div></section>
  <section className="inner-section locations-section"><p className="eyebrow">FIND J.BELLS</p><h2>Two places to<br /><span>find us.</span></h2><div className="location-mini-grid">{locations.map((location) => <a key={location.name} className="location-card" href={location.mapUrl} target="_blank" rel="noreferrer"><LineIcon name="search" /><div><h3>{location.name}</h3><p>{location.latitude}, {location.longitude}</p><span>Open in Google Maps <LineIcon name="arrowUpRight" /></span></div></a>)}</div></section>
 </PageShell> }
