'use client';
import Image from 'next/image';
import { HeroExperience } from '../components/HeroExperience';
import { LineIcon, IconName } from '../components/LineIcon';
import { Reveal } from '../components/Reveal';
import { SiteNav } from '../components/SiteChrome';
import { WhatsAppButton } from '../components/WhatsAppButton';
import { trackEvent } from '../lib/analytics';
import { businessContact } from '../lib/business';

const services: [string,string,string,IconName][] = [['01','DISPLAY REPAIR','Cracked or unresponsive screen? We replace the display assembly.','smartphone'],['02','BATTERY REPLACEMENT','Battery draining fast or swelling? We can swap the cell.','battery'],['03','CHARGING PORT REPAIR','Loose connector, debris, or no charge at all — we clean or replace the port.','usb'],['04','CAMERA & LENS REPAIR','Blurry shots, focus issues or cracked lens — we check the camera module.','camera'],['05','SPEAKER & MICROPHONE','Muffled calls or quiet audio — we test the speaker, mic and earpiece.','audio'],['06','SOFTWARE & HARDWARE','Stuck on a boot loop, forgot your PIN, or a hardware fault? We take a look.','cpu']];
const features: [string,string,string,IconName][] = [['01','DIAGNOSIS FIRST','We figure out what is actually wrong before we touch the phone.','scan'],['02','LOCAL BENCH','Repairs are carried out at our Trivandrum service counter.','wrench'],['03','CLEAR ESTIMATES','We explain the fault and the work needed before any repair begins.','check'],['04','SINCE 2010','A local smartphone service counter serving Trivandrum customers.','badge']];
function BrandLogo() { return <Image className="brand-logo" src="/android-chrome-192x192.png" alt="J Bells Smart Phone Service Center" width={192} height={192} priority />; }
function CTA({ location, children='Book a Repair' }: { location:string; children?:React.ReactNode }) { return <a className="button" href="#contact" onClick={()=>{trackEvent('hero_cta_clicked',{button_name:String(children),location});trackEvent('book_repair_clicked',{location})}}>{children}<LineIcon name="arrowUpRight"/></a>; }
export default function Home() { return <main>
  <SiteNav active="home" />
  <HeroExperience />
  <section className="trust section"><Reveal><p className="eyebrow">BUILT ON EXPERIENCE</p></Reveal><div className="trust-grid">{[['ISO 9001:2015','Quality Management System','shield'],['SINCE 2010','Serving Customers','calendar'],['SMARTPHONE SERVICE','Display, Battery, Port, Camera','smartphone'],['LOCAL COUNTER','A Walk-in Bench in Trivandrum','badge']].map(([title,detail,icon],i)=><Reveal key={title} delay={i*80} className="trust-item"><LineIcon name={icon as IconName}/><strong>{title}</strong><span>{detail}</span></Reveal>)}</div></section>
  <section className="intro section"><Reveal><p className="eyebrow">WHAT WE DO</p></Reveal><Reveal delay={100}><h2>Smartphone repairs,<br/><span>without the guesswork.</span></h2></Reveal><Reveal delay={180}><p className="body-copy">We look at the phone, tell you what is wrong, and only then talk about the repair. J Bells is a walk-in smartphone service center in Trivandrum handling everyday damage and more involved hardware faults.</p></Reveal></section>
  <section id="services" className="services section"><Reveal><div className="section-head"><div><p className="eyebrow">WHAT WE FIX</p><h2>Repairs for the<br/><span>problems phones get.</span></h2></div><p className="body-copy">A short list of the jobs we do most weeks. Bring the phone in and we will give you a straight answer.</p></div></Reveal><div className="service-list">{services.map(([n,t,d,icon],i)=><Reveal key={n} delay={i*60} className="service-reveal"><a href="#contact" onClick={()=>trackEvent('service_selected',{service_name:t==='SOFTWARE & HARDWARE'?'Software & Hardware Service':t})}><b>{n}</b><LineIcon name={icon}/><div><h3>{t}</h3><p>{d}</p></div><LineIcon name="arrowRight"/></a></Reveal>)}</div></section>
  <section id="about" className="about section"><div className="about-mark" aria-hidden="true">EST. 2010</div><Reveal><p className="eyebrow">ABOUT J BELLS</p><h2>A local phone<br/><span>repair bench.</span></h2></Reveal><Reveal delay={140}><div className="about-bottom"><p className="body-copy">J Bells is a walk-in smartphone service center in Thiruvananthapuram. We have been diagnosing, repairing and servicing phones since 2010, handling the common faults that come through our door.</p><div><p><LineIcon name="calendar"/>Serving Trivandrum since 2010.</p><p><LineIcon name="shield"/>ISO 9001:2015 certified.</p></div></div></Reveal></section>
  <section className="why section"><Reveal><p className="eyebrow">WHY CHOOSE US</p><h2>Diagnosis first,<br/><span>then the repair.</span></h2></Reveal><div className="feature-grid">{features.map(([n,t,d,icon],i)=><Reveal key={n} delay={i*80} className="feature-item"><b>{n}</b><LineIcon name={icon}/><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
  <section className="process section"><Reveal><p className="eyebrow">THE PROCESS</p><h2>How a repair<br/><span>works here.</span></h2></Reveal><div className="process-grid">{[['01','DIAGNOSE','We open the phone and find the fault.','search'],['02','REPAIR','We do the work at our bench and tell you if it will take a few hours or longer.','wrench'],['03','TEST','We check the part works before you take it.','check'],['04','RETURN','Pick up the phone in person at the counter.','smartphone']].map(([n,t,d,icon],i)=><Reveal key={n} delay={i*100} className="process-item"><b>{n}</b><LineIcon name={icon as IconName}/><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
  <section id="youtube" className="youtube section"><Reveal><div className="section-head"><div><p className="eyebrow">WATCH & LEARN</p><h2>See our work<br/><span>in action.</span></h2></div><p className="body-copy">Repair walkthroughs, teardown footage and a few things we have learned at the bench.</p></div></Reveal><Reveal delay={120}><a className="youtube-card" href={businessContact.youtube.href} target="_blank" rel="noreferrer" onClick={()=>trackEvent('youtube_channel_clicked',{location:'youtube_section'})}><div className="youtube-card-icon" aria-hidden="true"><LineIcon name="youtube"/></div><div className="youtube-card-copy"><p className="eyebrow">YOUTUBE CHANNEL</p><h3>Visit our YouTube channel</h3><p className="body-copy">{businessContact.youtube.handle} · Repair guides, teardown clips and the occasional smartphone-care tip from our Trivandrum bench.</p><span className="button youtube-card-cta">Watch Us on YouTube <LineIcon name="arrowUpRight"/></span></div></a></Reveal></section>
  <section id="contact" className="contact section"><Reveal><p className="eyebrow">START A CONVERSATION</p></Reveal><Reveal delay={100}><h2>Need a<br/><span>Repair?</span></h2></Reveal><Reveal delay={180}><p className="lede">Bring it in, or message us first. We will tell you what we think.</p></Reveal><Reveal delay={240}><div className="actions"><CTA location="final_cta"/><a className="text-link" href={businessContact.primaryPhone.tel} onClick={()=>trackEvent('contact_clicked',{contact_method:'phone',location:'final_cta'})}>Call {businessContact.primaryPhone.display} <LineIcon name="arrowUpRight"/></a></div></Reveal><Reveal delay={320}><div className="contact-details"><p><small>PHONE</small><a href={businessContact.primaryPhone.tel}>{businessContact.primaryPhone.display}</a></p><p><small>WHATSAPP</small><a href={businessContact.whatsapp.href} target="_blank" rel="noreferrer">Chat with us on WhatsApp</a></p><p><small>INSTAGRAM</small><a href={businessContact.instagram.href} target="_blank" rel="noreferrer">{businessContact.instagram.handle}</a></p></div></Reveal></section>
  <Reveal className="footer-reveal"><footer className="footer"><div className="footer-brand"><div className="brand"><BrandLogo /></div><p>{businessContact.businessName}</p></div><div><small className="footer-heading">SERVICES</small><div className="footer-links"><a href="/services">Services</a></div></div><div><small className="footer-heading">QUICK LINKS</small><div className="footer-links"><a href="#home">Home</a><a href="#about">About</a><a href="#contact">Contact</a></div></div><div><small className="footer-heading">FOLLOW US</small><div className="footer-social"><a href={businessContact.whatsapp.href} target="_blank" rel="noreferrer" aria-label="WhatsApp"><LineIcon name="whatsapp"/></a><a href={businessContact.instagram.href} target="_blank" rel="noreferrer" aria-label="Instagram"><LineIcon name="instagram"/></a><a href={businessContact.youtube.href} target="_blank" rel="noreferrer" aria-label="YouTube"><LineIcon name="youtube"/></a></div></div><small className="footer-copy">Copyright 2026 J Bells Smart Phone Service Center. All rights reserved.</small></footer></Reveal><WhatsAppButton />
 </main>; }
