'use client';
import Image from 'next/image';
import { HeroExperience } from '../components/HeroExperience';
import { LineIcon, IconName } from '../components/LineIcon';
import { Reveal } from '../components/Reveal';
import { SiteNav } from '../components/SiteChrome';
import { WhatsAppButton } from '../components/WhatsAppButton';
import { trackEvent } from '../lib/analytics';
import { businessContact } from '../lib/business';

const services: [string,string,string,IconName][] = [['01','DISPLAY REPAIR','Professional display replacement for damaged or cracked screens.','smartphone'],['02','BATTERY REPLACEMENT','Restore battery performance with professional replacement.','battery'],['03','CHARGING PORT REPAIR','Resolve charging and connectivity problems.','usb'],['04','CAMERA & LENS REPAIR','Professional repair for camera and lens issues.','camera'],['05','SPEAKER & MICROPHONE','Restore clear audio and call quality.','audio'],['06','SOFTWARE & HARDWARE','Diagnosis and repair for software and hardware problems.','cpu']];
const features: [string,string,string,IconName][] = [['01','PRECISE DIAGNOSIS','Understand the actual problem before beginning the repair.','scan'],['02','PROFESSIONAL SERVICE','Careful handling and attention to every repair.','wrench'],['03','QUALITY WORKMANSHIP','Repairs performed with precision and consistency.','check'],['04','TRUSTED EXPERIENCE','Serving customers since 2010.','badge']];
function BrandLogo() { return <Image className="brand-logo" src="/android-chrome-192x192.png" alt="J Bells Service Center" width={192} height={192} priority />; }
function CTA({ location, children='Book a Repair' }: { location:string; children?:React.ReactNode }) { return <a className="button" href="#contact" onClick={()=>{trackEvent('hero_cta_clicked',{button_name:String(children),location});trackEvent('book_repair_clicked',{location})}}>{children}<LineIcon name="arrowUpRight"/></a>; }
export default function Home() { return <main>
  <SiteNav active="home" />
  <HeroExperience />
  <section className="trust section"><Reveal><p className="eyebrow">BUILT ON EXPERIENCE</p></Reveal><div className="trust-grid">{[['ISO CERTIFIED','Service Center','shield'],['SINCE 2010','Serving Customers','calendar'],['SMARTPHONE SERVICE','Specialized Repair','smartphone'],['PROFESSIONAL CARE','Precise Workmanship','badge']].map(([title,detail,icon],i)=><Reveal key={title} delay={i*80} className="trust-item"><LineIcon name={icon as IconName}/><strong>{title}</strong><span>{detail}</span></Reveal>)}</div></section>
  <section className="intro section"><Reveal><p className="eyebrow">WHAT WE DO</p></Reveal><Reveal delay={100}><h2>Professional smartphone service,<br/><span>from diagnosis to repair.</span></h2></Reveal><Reveal delay={180}><p className="body-copy">From everyday damage to complex hardware issues, J Bells Service Center provides careful diagnosis, repair, and servicing for your smartphone.</p></Reveal></section>
  <section id="services" className="services section"><Reveal><div className="section-head"><div><p className="eyebrow">OUR EXPERTISE</p><h2>Expertise for<br/><span>Every Repair</span></h2></div><p className="body-copy">Professional service for the problems your smartphone can face.</p></div></Reveal><div className="service-list">{services.map(([n,t,d,icon],i)=><Reveal key={n} delay={i*60} className="service-reveal"><a href="#contact" onClick={()=>trackEvent('service_selected',{service_name:t==='SOFTWARE & HARDWARE'?'Software & Hardware Service':t})}><b>{n}</b><LineIcon name={icon}/><div><h3>{t}</h3><p>{d}</p></div><LineIcon name="arrowRight"/></a></Reveal>)}</div></section>
  <section id="about" className="about section"><div className="about-mark" aria-hidden="true">EST. 2010</div><Reveal><p className="eyebrow">ABOUT J BELLS</p><h2>Built around<br/><span>better repairs.</span></h2></Reveal><Reveal delay={140}><div className="about-bottom"><p className="body-copy">J Bells Service Center is focused on professional smartphone servicing, combining careful diagnosis, technical expertise, and precision repair to keep your device working at its best.</p><div><p><LineIcon name="calendar"/>Serving since 2010.</p><p><LineIcon name="shield"/>ISO Certified Service Center.</p></div></div></Reveal></section>
  <section className="why section"><Reveal><p className="eyebrow">WHY CHOOSE US</p><h2>Precision inside<br/><span>and out.</span></h2></Reveal><div className="feature-grid">{features.map(([n,t,d,icon],i)=><Reveal key={n} delay={i*80} className="feature-item"><b>{n}</b><LineIcon name={icon}/><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
  <section className="process section"><Reveal><p className="eyebrow">THE PROCESS</p><h2>From diagnosis<br/><span>to done.</span></h2></Reveal><div className="process-grid">{[['01','DIAGNOSE','Identify the problem.','search'],['02','REPAIR','Perform the required service.','wrench'],['03','TEST','Verify the device is working correctly.','check'],['04','RETURN','Get your phone back ready to use.','smartphone']].map(([n,t,d,icon],i)=><Reveal key={n} delay={i*100} className="process-item"><b>{n}</b><LineIcon name={icon as IconName}/><h3>{t}</h3><p>{d}</p></Reveal>)}</div></section>
  <section id="youtube" className="youtube section"><Reveal><div className="section-head"><div><p className="eyebrow">WATCH & LEARN</p><h2>See our work<br/><span>in action.</span></h2></div><p className="body-copy">Repair walkthroughs, device-care tips and behind-the-scenes looks at how we service every phone that comes through the door.</p></div></Reveal><Reveal delay={120}><a className="youtube-card" href={businessContact.youtube.href} target="_blank" rel="noreferrer" onClick={()=>trackEvent('youtube_channel_clicked',{location:'youtube_section'})}><div className="youtube-card-icon" aria-hidden="true"><LineIcon name="youtube"/></div><div className="youtube-card-copy"><p className="eyebrow">YOUTUBE CHANNEL</p><h3>Visit our YouTube channel</h3><p className="body-copy">{businessContact.youtube.handle} · Subscribe for repair guides, teardown footage and practical smartphone-care advice from the J Bells bench.</p><span className="button youtube-card-cta">Watch Us on YouTube <LineIcon name="arrowUpRight"/></span></div></a></Reveal></section>
  <section id="contact" className="contact section"><Reveal><p className="eyebrow">START A CONVERSATION</p></Reveal><Reveal delay={100}><h2>Need a<br/><span>Repair?</span></h2></Reveal><Reveal delay={180}><p className="lede">Let us get your phone back to its best.</p></Reveal><Reveal delay={240}><div className="actions"><CTA location="final_cta"/><a className="text-link" href={businessContact.primaryPhone.tel} onClick={()=>trackEvent('contact_clicked',{contact_method:'phone',location:'final_cta'})}>Call {businessContact.primaryPhone.display} <LineIcon name="arrowUpRight"/></a></div></Reveal><Reveal delay={320}><div className="contact-details"><p><small>PHONE</small><a href={businessContact.primaryPhone.tel}>{businessContact.primaryPhone.display}</a></p><p><small>WHATSAPP</small><a href={businessContact.whatsapp.href} target="_blank" rel="noreferrer">Chat with us on WhatsApp</a></p><p><small>INSTAGRAM</small><a href={businessContact.instagram.href} target="_blank" rel="noreferrer">{businessContact.instagram.handle}</a></p></div></Reveal></section>
  <Reveal className="footer-reveal"><footer className="footer"><div className="footer-brand"><div className="brand"><BrandLogo /></div><p>{businessContact.businessName}</p></div><div><small className="footer-heading">SERVICES</small><div className="footer-links"><a href="/services">Services</a></div></div><div><small className="footer-heading">QUICK LINKS</small><div className="footer-links"><a href="#home">Home</a><a href="#about">About</a><a href="#contact">Contact</a></div></div><div><small className="footer-heading">FOLLOW US</small><div className="footer-social"><a href={businessContact.whatsapp.href} target="_blank" rel="noreferrer" aria-label="WhatsApp"><LineIcon name="whatsapp"/></a><a href={businessContact.instagram.href} target="_blank" rel="noreferrer" aria-label="Instagram"><LineIcon name="instagram"/></a><a href={businessContact.youtube.href} target="_blank" rel="noreferrer" aria-label="YouTube"><LineIcon name="youtube"/></a></div></div><small className="footer-copy">Copyright 2026 J Bells Service Center. All rights reserved.</small></footer></Reveal><WhatsAppButton />
 </main>; }
